// Fight the Heavens

///////////////////////////////////////////////////////////////////////////
// Update Oasis Script                                                   //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME "AR6300.BCS" BEGIN
    EXTEND_BOTTOM ~AR6300.bcs~ ~fight-the-heavens/baf/ar6300.baf~
END ELSE BEGIN
    COPY ~fight-the-heavens/baf/AR6300.baf~  ~override/AR6300.bcs~
        COMPILE_BAF_TO_BCS
END

///////////////////////////////////////////////////////////////////////////
// Update Dorn's Forest Clearing Script                                  //
///////////////////////////////////////////////////////////////////////////
EXTEND_BOTTOM ~OH5400.bcs~ ~fight-the-heavens/baf/oh5400.baf~
COMPILE EVALUATE_BUFFER ~fight-the-heavens/dlg/ohdplanj.d~ 